"""baseline_initial_schema

Revision ID: 101b1dc45309
Revises:
Create Date: 2026-07-29 14:53:23.485664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101b1dc45309'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-written, not autogenerated: ORM metadata reflects the FINAL schema
    state, not this intermediate one. This recreates database/schema.sql's
    current structure MINUS everything already added by an existing
    migration further down the chain (those run after this one and would
    otherwise collide) — see CLAUDE.md > Database Rules > Schema/Alembic
    Parity Verification for the full exclusion list. DDL only, no seed
    data (seeding is `python -m app.core.seed`; schema.sql's own seed rows
    for role/payment_method are outside pg_dump --schema-only's scope
    entirely and are not this migration's concern).

    Excluded here because a later migration in the chain creates it:
      - product_audit_log table + product_change_type_enum      (d4a1f7c3b9e6)
      - user_audit_log table + user_change_type_enum             (76d3a5dc2561)
      - transaction_item_audit_log table + item_edit_source_enum (a3d6f8c1e9b4)
      - transaction_item.unit_count                              (1315883b38d2)
      - transaction_item.quantity_kg                              (a4f7c2e9b1d3)
      - transaction_item.actual_unit_count/actual_quantity_kg/
        actual_subtotal                                          (3623cd0e88d3)
      - payment_detail.is_draft                                   (c9d1e5f3a7b2)
      - payment_detail.draft_balances_json/draft_credit_applied/
        draft_credit_sources_json                    (d2f4a8b6e1c9/f3b8c6d1a9e2/a7c3f9e2d5b1)
      - sales_transaction.change_claimed                          (e5a2c7f1b3d8)
      - sales_transaction.original_items_snapshot                 (bfa2c83f3989)
      - sales_transaction.items_edited_at_payment                 (e1b4d7a9c2f6)
      - sales_transaction.original_items_snapshot_archive         (f7c2a9e4d6b1)
      - customer.created_by_user_id                               (d9a92d9d4b55)

    transaction_status_enum starts at its pre-'pending_edit' 5 values;
    'pending_adjustment'/'pending_handover' are added later
    (a1c5e8f2b4d6/b2e6f4a8d1c7), 'pending_edit' itself is added and then
    removed later still (b7e3f9a1c2d4/9c4f2a7e5d3b) and never belongs here.

    transaction_type_enum starts WITH 'credit_usage' — it existed at this
    point historically and is only dropped later (c4e8a1f6b3d5).
    """

    # -----------------------------------------------------------------
    # Trigger function (used by every *_updated_at trigger below)
    # -----------------------------------------------------------------
    # Not indented to match the def body above: Postgres stores a plpgsql
    # function's source as literal text (prosrc) and pg_dump reproduces it
    # verbatim, so this has to match schema.sql's exact formatting byte for
    # byte or verify-schema-parity.ps1 flags a false-positive whitespace diff.
    op.execute(
        "CREATE OR REPLACE FUNCTION set_updated_at()\n"
        "RETURNS TRIGGER AS $$\n"
        "BEGIN\n"
        "    NEW.updated_at = NOW();\n"
        "    RETURN NEW;\n"
        "END;\n"
        "$$ LANGUAGE plpgsql;"
    )

    # -----------------------------------------------------------------
    # Enums (only the ones not created by a later migration)
    # -----------------------------------------------------------------
    op.execute("CREATE TYPE customer_status_enum AS ENUM ('active', 'inactive')")
    op.execute("CREATE TYPE product_status_enum AS ENUM ('active', 'inactive')")
    op.execute("CREATE TYPE customer_type_enum AS ENUM ('walk_in', 'online')")
    op.execute("""
        CREATE TYPE transaction_status_enum AS ENUM (
            'pending_payment', 'pending_settlement', 'settled', 'completed', 'voided'
        )
    """)
    op.execute("""
        CREATE TYPE transaction_type_enum AS ENUM (
            'original', 'adjustment', 'refund', 'balance_settlement', 'credit_usage'
        )
    """)
    op.execute("CREATE TYPE queue_status_enum AS ENUM ('waiting', 'processing', 'parked', 'done')")
    op.execute("CREATE TYPE item_type_enum AS ENUM ('product', 'balance_settlement', 'credit_usage')")
    op.execute("""
        CREATE TYPE ledger_entry_type_enum AS ENUM (
            'balance_added', 'balance_settled', 'credit_added', 'credit_used', 'credit_auto_used'
        )
    """)
    op.execute("CREATE TYPE audit_change_type_enum AS ENUM ('transaction_status', 'queue_status')")

    # -----------------------------------------------------------------
    # role
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE role (
            id        SERIAL PRIMARY KEY,
            role_name VARCHAR(50) NOT NULL UNIQUE
        )
    """)

    # -----------------------------------------------------------------
    # user
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE "user" (
            id            SERIAL PRIMARY KEY,
            full_name     VARCHAR(100) NOT NULL,
            username      VARCHAR(50)  NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            role_id       INT          NOT NULL REFERENCES role(id) ON DELETE RESTRICT,
            is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
            created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
            updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("""
        CREATE TRIGGER trg_user_updated_at
            BEFORE UPDATE ON "user"
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    """)

    # -----------------------------------------------------------------
    # customer (minus created_by_user_id — d9a92d9d4b55)
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE customer (
            id              SERIAL PRIMARY KEY,
            full_name       VARCHAR(100)         NOT NULL,
            address         VARCHAR(255),
            contact_number  VARCHAR(20),
            customer_status customer_status_enum NOT NULL DEFAULT 'active',
            net_balance     DECIMAL(10,2)        NOT NULL DEFAULT 0.00,
            created_at      TIMESTAMPTZ          NOT NULL DEFAULT NOW(),
            updated_at      TIMESTAMPTZ          NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_customer_status ON customer (customer_status)")
    op.execute("""
        CREATE TRIGGER trg_customer_updated_at
            BEFORE UPDATE ON customer
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    """)

    # -----------------------------------------------------------------
    # product
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE product (
            id              SERIAL PRIMARY KEY,
            product_name    VARCHAR(100)        NOT NULL,
            brand_name      VARCHAR(100),
            unit_weight_kg  DECIMAL(10,3),
            unit_price_php  DECIMAL(10,2)       NOT NULL,
            stock_quantity  DECIMAL(10,3)       NOT NULL DEFAULT 0,
            product_status  product_status_enum NOT NULL DEFAULT 'active',
            created_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW(),
            updated_at      TIMESTAMPTZ         NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_product_status ON product (product_status)")
    op.execute("""
        CREATE TRIGGER trg_product_updated_at
            BEFORE UPDATE ON product
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    """)

    # -----------------------------------------------------------------
    # payment_method
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE payment_method (
            id                  SERIAL PRIMARY KEY,
            payment_method_name VARCHAR(50) NOT NULL UNIQUE
        )
    """)

    # -----------------------------------------------------------------
    # sales_transaction (minus change_claimed, original_items_snapshot,
    # items_edited_at_payment, original_items_snapshot_archive)
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE sales_transaction (
            id                    SERIAL PRIMARY KEY,
            order_number          VARCHAR(50)              NOT NULL UNIQUE,

            parent_transaction_id INT                      NULL REFERENCES sales_transaction(id) ON DELETE RESTRICT,

            transaction_type      transaction_type_enum    NOT NULL,
            transaction_status    transaction_status_enum  NOT NULL,

            customer_type         customer_type_enum       NOT NULL DEFAULT 'walk_in',

            walkin_user_id        INT                      NULL REFERENCES "user"(id) ON DELETE RESTRICT,
            payment_user_id       INT                      NULL REFERENCES "user"(id) ON DELETE RESTRICT,
            releasing_user_id     INT                      NULL REFERENCES "user"(id) ON DELETE RESTRICT,

            customer_id           INT                      NOT NULL REFERENCES customer(id) ON DELETE RESTRICT,

            estimated_amount      DECIMAL(10,2)            NOT NULL DEFAULT 0.00,

            actual_amount         DECIMAL(10,2)            NULL,

            balance_due           DECIMAL(10,2)            GENERATED ALWAYS AS (
                                      CASE
                                          WHEN actual_amount IS NOT NULL
                                          THEN actual_amount - estimated_amount
                                          ELSE NULL
                                      END
                                  ) STORED,

            credit_applied        DECIMAL(10,2)            NOT NULL DEFAULT 0.00,

            balance_settled       DECIMAL(10,2)            NOT NULL DEFAULT 0.00,

            total_due             DECIMAL(10,2)            NOT NULL DEFAULT 0.00,

            cash_tendered         DECIMAL(10,2)            NOT NULL DEFAULT 0.00,

            change_given          DECIMAL(10,2)            NOT NULL DEFAULT 0.00,

            invoice_pdf           VARCHAR(255)             NULL,

            walkin_at             TIMESTAMPTZ              NULL,
            payment_at            TIMESTAMPTZ              NULL,
            releasing_at          TIMESTAMPTZ              NULL,

            queue_status          queue_status_enum        NOT NULL DEFAULT 'waiting',

            processing_by_user_id INT                      NULL REFERENCES "user"(id) ON DELETE RESTRICT,

            processing_started_at TIMESTAMPTZ              NULL,

            parked_by_user_id     INT                      NULL REFERENCES "user"(id) ON DELETE RESTRICT,

            parked_at             TIMESTAMPTZ              NULL,

            created_at            TIMESTAMPTZ              NOT NULL DEFAULT NOW(),
            updated_at            TIMESTAMPTZ              NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_st_parent_transaction ON sales_transaction (parent_transaction_id)")
    op.execute("CREATE INDEX idx_st_transaction_status ON sales_transaction (transaction_status)")
    op.execute("CREATE INDEX idx_st_transaction_type ON sales_transaction (transaction_type)")
    op.execute("CREATE INDEX idx_st_customer ON sales_transaction (customer_id)")
    op.execute("CREATE INDEX idx_st_queue_status ON sales_transaction (queue_status)")
    op.execute("CREATE INDEX idx_st_customer_type ON sales_transaction (customer_type)")
    op.execute("CREATE INDEX idx_st_processing_by ON sales_transaction (processing_by_user_id)")
    op.execute("CREATE INDEX idx_st_parked_by ON sales_transaction (parked_by_user_id)")
    op.execute("""
        CREATE TRIGGER trg_sales_transaction_updated_at
            BEFORE UPDATE ON sales_transaction
            FOR EACH ROW EXECUTE FUNCTION set_updated_at()
    """)

    # -----------------------------------------------------------------
    # transaction_item (minus unit_count, quantity_kg, actual_unit_count,
    # actual_quantity_kg, actual_subtotal)
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE transaction_item (
            id                       SERIAL PRIMARY KEY,
            transaction_id           INT            NOT NULL REFERENCES sales_transaction(id) ON DELETE CASCADE,

            item_type                item_type_enum NOT NULL DEFAULT 'product',

            product_id               INT            NULL REFERENCES product(id) ON DELETE RESTRICT,

            estimated_weight_kg      DECIMAL(10,3)  NULL,

            actual_weight_kg         DECIMAL(10,3)  NULL,

            unit_price               DECIMAL(10,2)  NULL,

            reference_transaction_id INT            NULL REFERENCES sales_transaction(id) ON DELETE RESTRICT,

            subtotal                 DECIMAL(10,2)  NOT NULL DEFAULT 0.00
        )
    """)
    op.execute("CREATE INDEX idx_ti_transaction ON transaction_item (transaction_id)")
    op.execute("CREATE INDEX idx_ti_item_type ON transaction_item (item_type)")

    # -----------------------------------------------------------------
    # payment_detail (minus is_draft, draft_balances_json,
    # draft_credit_applied, draft_credit_sources_json)
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE payment_detail (
            id                SERIAL PRIMARY KEY,
            transaction_id    INT           NOT NULL REFERENCES sales_transaction(id) ON DELETE CASCADE,
            payment_method_id INT           NOT NULL REFERENCES payment_method(id)    ON DELETE RESTRICT,
            ref_number        VARCHAR(100)  NULL,
            tendered_amount   DECIMAL(10,2) NULL,
            amount            DECIMAL(10,2) NOT NULL,
            created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_pd_transaction ON payment_detail (transaction_id)")

    # -----------------------------------------------------------------
    # customer_ledger
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE customer_ledger (
            id              SERIAL PRIMARY KEY,
            customer_id     INT                    NOT NULL REFERENCES customer(id)           ON DELETE RESTRICT,
            transaction_id  INT                    NOT NULL REFERENCES sales_transaction(id)  ON DELETE CASCADE,

            entry_type      ledger_entry_type_enum NOT NULL,

            amount          DECIMAL(10,2)          NOT NULL,

            running_balance DECIMAL(10,2)          NOT NULL,

            notes           VARCHAR(255)           NULL,
            created_at      TIMESTAMPTZ            NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_cl_customer ON customer_ledger (customer_id)")
    op.execute("CREATE INDEX idx_cl_transaction ON customer_ledger (transaction_id)")

    # -----------------------------------------------------------------
    # transaction_void_log
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE transaction_void_log (
            id                SERIAL PRIMARY KEY,
            transaction_id    INT         NOT NULL REFERENCES sales_transaction(id) ON DELETE CASCADE,
            void_reason       TEXT        NOT NULL,
            voided_by_user_id INT         NOT NULL REFERENCES "user"(id)            ON DELETE RESTRICT,
            voided_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)

    # -----------------------------------------------------------------
    # transaction_audit_log
    # -----------------------------------------------------------------
    op.execute("""
        CREATE TABLE transaction_audit_log (
            id                 SERIAL PRIMARY KEY,
            transaction_id     INT                    NOT NULL REFERENCES sales_transaction(id) ON DELETE CASCADE,
            changed_by_user_id INT                    NOT NULL REFERENCES "user"(id)            ON DELETE RESTRICT,

            change_type        audit_change_type_enum NOT NULL,

            old_value          VARCHAR(50)            NULL,
            new_value          VARCHAR(50)            NOT NULL,

            notes              TEXT                   NULL,
            changed_at         TIMESTAMPTZ            NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_tal_transaction ON transaction_audit_log (transaction_id)")
    op.execute("CREATE INDEX idx_tal_change_type ON transaction_audit_log (change_type)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE IF EXISTS transaction_audit_log")
    op.execute("DROP TABLE IF EXISTS transaction_void_log")
    op.execute("DROP TABLE IF EXISTS customer_ledger")
    op.execute("DROP TABLE IF EXISTS payment_detail")
    op.execute("DROP TABLE IF EXISTS transaction_item")
    op.execute("DROP TABLE IF EXISTS sales_transaction")
    op.execute("DROP TABLE IF EXISTS payment_method")
    op.execute("DROP TABLE IF EXISTS product")
    op.execute("DROP TABLE IF EXISTS customer")
    op.execute('DROP TABLE IF EXISTS "user"')
    op.execute("DROP TABLE IF EXISTS role")

    op.execute("DROP TYPE IF EXISTS audit_change_type_enum")
    op.execute("DROP TYPE IF EXISTS ledger_entry_type_enum")
    op.execute("DROP TYPE IF EXISTS item_type_enum")
    op.execute("DROP TYPE IF EXISTS queue_status_enum")
    op.execute("DROP TYPE IF EXISTS transaction_type_enum")
    op.execute("DROP TYPE IF EXISTS transaction_status_enum")
    op.execute("DROP TYPE IF EXISTS customer_type_enum")
    op.execute("DROP TYPE IF EXISTS product_status_enum")
    op.execute("DROP TYPE IF EXISTS customer_status_enum")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")
